"""add photographer_slug to studio_collections

Revision ID: 74b3084940a4
Revises: 5c55ba9d3130
Create Date: 2026-07-02 10:21:41.023643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '74b3084940a4'
down_revision = '5c55ba9d3130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_payouts', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('artist_payouts', 'related_tip_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('content_artist_album_tracks', 'track_id_ref',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_album_tracks', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_album_tracks', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'release_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'cover_art',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'tags',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'show_ref_id',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'show_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'duration',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'category',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'published_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'track_ref_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'album',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'duration',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'genre',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'added_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'name',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'artist_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'image',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'social_links',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'genres',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'followers',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'created_at_str',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'updated_at_str',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_artists', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'time',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'venue',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'venue_address',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('content_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=5000),
               existing_nullable=False)
    op.alter_column('content_events', 'photos',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'image',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'rsvp_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_events', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_merch', 'name',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_merch', 'image_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_merch', 'price_usd',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_merch', 'kind',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_merch', 'available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_merch', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'duration',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'audio_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'artwork',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'video_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default='',
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'artwork',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'last_updated',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'host',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'video_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'thumbnail',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'published_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'views',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'show_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'is_live',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'tags',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'category',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_shows', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'artist',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'album',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'genre',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'audio_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'preview_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'cover_art',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'added_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'tags',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'artist_slug',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_tracks', 'play_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_videos', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_videos', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_videos', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_videos', 'thumbnail',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_videos', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_whats_new', 'item_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_whats_new', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_whats_new', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_whats_new', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_whats_new', 'skip_feature',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('content_whats_new', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('feedback', 'type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('listening_sessions', 'seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('listening_sessions', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('listening_totals', 'total_seconds',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('play_history', 'progress_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('playlists', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('poems', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchases', 'qty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchases', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('purchases', 'total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('purchases', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('radio_prefs', 'seed_tags',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.add_column('studio_collections', sa.Column('photographer_slug', sa.String(length=255), nullable=True))
    op.alter_column('studio_collections', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('studio_collections', 'date',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('studio_collections', 'tag',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('studio_collections', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=None,
               existing_nullable=False)
    op.alter_column('studio_collections', 'cover',
               existing_type=sa.VARCHAR(length=1024),
               server_default=None,
               existing_nullable=False)
    op.alter_column('studio_collections', 'photos',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('studio_collections', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_studio_collections_photographer_slug'), 'studio_collections', ['photographer_slug'], unique=False)
    op.alter_column('tips', 'fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('tips', 'net_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('user_artist_positions', 'total_contributed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_wallet_transactions_type'), table_name='wallet_transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wallet_transactions_type'), 'wallet_transactions', ['type'], unique=False)
    op.alter_column('users', 'preferences',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'{}'"),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_artist_positions', 'total_contributed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('tips', 'net_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('tips', 'fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_studio_collections_photographer_slug'), table_name='studio_collections')
    op.alter_column('studio_collections', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('studio_collections', 'photos',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('studio_collections', 'cover',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('studio_collections', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('studio_collections', 'tag',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('studio_collections', 'date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('studio_collections', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.drop_column('studio_collections', 'photographer_slug')
    op.alter_column('radio_prefs', 'seed_tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('purchases', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    op.alter_column('purchases', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('purchases', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('purchases', 'qty',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.alter_column('poems', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('playlists', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'private'"),
               existing_nullable=False)
    op.alter_column('play_history', 'progress_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('listening_totals', 'total_seconds',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('listening_sessions', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'manual'"),
               existing_nullable=False)
    op.alter_column('listening_sessions', 'seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('feedback', 'type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'general'"),
               existing_nullable=False)
    op.alter_column('content_whats_new', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_whats_new', 'skip_feature',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_whats_new', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_whats_new', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_whats_new', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_whats_new', 'item_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'content'"),
               existing_nullable=False)
    op.alter_column('content_videos', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_videos', 'thumbnail',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_videos', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'coming_soon'"),
               existing_nullable=False)
    op.alter_column('content_videos', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_videos', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'play_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'artist_slug',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'added_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'cover_art',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'preview_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'audio_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'genre',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'album',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'artist',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_tracks', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_shows', 'category',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('content_shows', 'is_live',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('content_shows', 'show_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'views',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_shows', 'published_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'thumbnail',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'video_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'host',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_shows', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'last_updated',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'artwork',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_shows', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'video_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'artwork',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'audio_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'duration',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_podcast_episodes', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_merch', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_merch', 'available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               existing_nullable=False)
    op.alter_column('content_merch', 'kind',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'merch'"),
               existing_nullable=False)
    op.alter_column('content_merch', 'price_usd',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'20.0'"),
               existing_nullable=False)
    op.alter_column('content_merch', 'image_url',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_merch', 'name',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_events', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_events', 'rsvp_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'true'"),
               existing_nullable=False)
    op.alter_column('content_events', 'image',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_events', 'photos',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('content_events', 'description',
               existing_type=sa.String(length=5000),
               server_default=sa.text("('')"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('content_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'upcoming'"),
               existing_nullable=False)
    op.alter_column('content_events', 'event_type',
               existing_type=sa.String(length=50),
               server_default=sa.text("('')"),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('content_events', 'venue_address',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_events', 'venue',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_events', 'time',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_events', 'date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_events', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artists', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artists', 'updated_at_str',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artists', 'created_at_str',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artists', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('content_artists', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('content_artists', 'followers',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artists', 'genres',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('content_artists', 'social_links',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'{}'"),
               existing_nullable=False)
    op.alter_column('content_artists', 'image',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artists', 'description',
               existing_type=sa.VARCHAR(length=5000),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artists', 'artist_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artists', 'name',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'added_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'genre',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'duration',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'album',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_tracks', 'track_ref_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'published_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'category',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'duration',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'show_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_shows', 'show_ref_id',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'is_new',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'false'"),
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'tags',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'cover_art',
               existing_type=sa.VARCHAR(length=1024),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'release_date',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_albums', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_album_tracks', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('content_artist_album_tracks', 'title',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('content_artist_album_tracks', 'track_id_ref',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('artist_payouts', 'related_tip_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('artist_payouts', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    # ### end Alembic commands ###
