"""Add feedback type and claim code

Revision ID: 98939985b910
Revises: 0024_videos_whats_new
Create Date: 2026-02-19 21:52:20.373238

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '98939985b910'
down_revision = '0024_videos_whats_new'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('type', sa.String(length=50), nullable=False, server_default='general'))
    op.add_column('feedback', sa.Column('claim_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'claim_code')
    op.drop_column('feedback', 'type')
    # ### end Alembic commands ###
