#!/bin/bash
# Stripe Setup Automation Script
# This script automates what can be done via terminal/CLI

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 Stripe Setup Automation${NC}"
echo ""

# Check if Stripe CLI is installed
if ! command -v stripe &> /dev/null; then
    echo -e "${YELLOW}⚠️  Stripe CLI not found. Installing...${NC}"
    echo ""
    echo "Please install Stripe CLI first:"
    echo "  macOS: brew install stripe/stripe-cli/stripe"
    echo "  Linux: https://github.com/stripe/stripe-cli/releases"
    echo "  Windows: https://github.com/stripe/stripe-cli/releases"
    echo ""
    exit 1
fi

# Check if user is logged in to Stripe CLI
if ! stripe config --list &> /dev/null; then
    echo -e "${YELLOW}⚠️  Not logged in to Stripe CLI${NC}"
    echo "Run: stripe login"
    exit 1
fi

# Get environment (test or live)
read -p "Environment (test/live) [test]: " ENV
ENV=${ENV:-test}

if [ "$ENV" = "live" ]; then
    MODE="live"
    API_KEY_VAR="STRIPE_SECRET_KEY"
    PUBLISHABLE_VAR="STRIPE_PUBLISHABLE_KEY"
    WEBHOOK_SECRET_VAR="STRIPE_WEBHOOK_SECRET"
else
    MODE="test"
    API_KEY_VAR="STRIPE_SECRET_KEY_TEST"
    PUBLISHABLE_VAR="STRIPE_PUBLISHABLE_KEY_TEST"
    WEBHOOK_SECRET_VAR="STRIPE_WEBHOOK_SECRET_TEST"
fi

echo ""
echo -e "${BLUE}📋 Step 1: Getting API Keys${NC}"
echo ""

# Get API keys from Stripe CLI
echo "Fetching API keys from Stripe..."
SECRET_KEY=$(stripe config --get test_mode_api_key 2>/dev/null || stripe config --get live_mode_api_key 2>/dev/null || echo "")
PUBLISHABLE_KEY=$(stripe config --get test_mode_publishable_key 2>/dev/null || stripe config --get live_mode_publishable_key 2>/dev/null || echo "")

if [ -z "$SECRET_KEY" ] || [ -z "$PUBLISHABLE_KEY" ]; then
    echo -e "${RED}❌ Could not fetch API keys from Stripe CLI config${NC}"
    echo ""
    echo "You need to manually get these from Stripe Dashboard:"
    echo "  1. Go to https://dashboard.stripe.com/apikeys"
    echo "  2. Switch to ${MODE} mode"
    echo "  3. Copy the Publishable key and Secret key"
    echo ""
    read -p "Enter Publishable Key: " PUBLISHABLE_KEY
    read -p "Enter Secret Key: " SECRET_KEY
fi

echo -e "${GREEN}✅ API Keys retrieved${NC}"
echo ""

# Get webhook URL
read -p "Enter your production BASE_URL (e.g., https://app.ahoy.ooo): " BASE_URL
WEBHOOK_URL="${BASE_URL}/webhooks/stripe"

echo ""
echo -e "${BLUE}📋 Step 2: Creating Webhook Endpoint${NC}"
echo ""

# Create webhook endpoint via Stripe API
echo "Creating webhook endpoint: ${WEBHOOK_URL}"

WEBHOOK_RESPONSE=$(stripe webhook_endpoints create \
    --url "$WEBHOOK_URL" \
    --enabled-events checkout.session.completed \
    --enabled-events payment_intent.succeeded \
    --api-key "$SECRET_KEY" \
    --format json 2>&1)

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Failed to create webhook endpoint${NC}"
    echo "$WEBHOOK_RESPONSE"
    echo ""
    echo "You may need to create it manually in the Dashboard:"
    echo "  1. Go to https://dashboard.stripe.com/webhooks"
    echo "  2. Click 'Add endpoint'"
    echo "  3. URL: ${WEBHOOK_URL}"
    echo "  4. Events: checkout.session.completed, payment_intent.succeeded"
    exit 1
fi

# Extract webhook secret from response
WEBHOOK_SECRET=$(echo "$WEBHOOK_RESPONSE" | grep -o '"secret":"[^"]*"' | cut -d'"' -f4 || echo "")

if [ -z "$WEBHOOK_SECRET" ]; then
    # Try alternative parsing
    WEBHOOK_SECRET=$(echo "$WEBHOOK_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('secret', ''))" 2>/dev/null || echo "")
fi

if [ -z "$WEBHOOK_SECRET" ]; then
    echo -e "${YELLOW}⚠️  Could not extract webhook secret automatically${NC}"
    echo "Response: $WEBHOOK_RESPONSE"
    echo ""
    echo "Please get it manually from:"
    echo "  https://dashboard.stripe.com/webhooks"
    read -p "Enter Webhook Secret (whsec_...): " WEBHOOK_SECRET
fi

echo -e "${GREEN}✅ Webhook endpoint created${NC}"
echo "  URL: ${WEBHOOK_URL}"
echo "  Secret: ${WEBHOOK_SECRET:0:20}..."
echo ""

# Generate .env file
echo -e "${BLUE}📋 Step 3: Generating Environment Variables${NC}"
echo ""

ENV_FILE=".env.stripe.${MODE}"
cat > "$ENV_FILE" << EOF
# Stripe Configuration (${MODE} mode)
# Generated by setup_stripe.sh on $(date)

AHOY_ENV=$([ "$MODE" = "live" ] && echo "production" || echo "development")
${PUBLISHABLE_VAR}=${PUBLISHABLE_KEY}
${API_KEY_VAR}=${SECRET_KEY}
${WEBHOOK_SECRET_VAR}=${WEBHOOK_SECRET}
EOF

echo -e "${GREEN}✅ Environment variables saved to ${ENV_FILE}${NC}"
echo ""
echo "To use these variables:"
echo "  export \$(cat ${ENV_FILE} | xargs)"
echo ""
echo "Or add them to your deployment platform (Render, Heroku, etc.)"
echo ""

# Test webhook (optional)
read -p "Test webhook endpoint? (y/n) [n]: " TEST_WEBHOOK
if [ "$TEST_WEBHOOK" = "y" ]; then
    echo ""
    echo -e "${BLUE}📋 Step 4: Testing Webhook${NC}"
    echo ""
    echo "Triggering test event..."
    stripe trigger checkout.session.completed --api-key "$SECRET_KEY" || echo "Test event sent (check your server logs)"
fi

echo ""
echo -e "${GREEN}✅ Stripe setup complete!${NC}"
echo ""
echo "Summary:"
echo "  Mode: ${MODE}"
echo "  Webhook URL: ${WEBHOOK_URL}"
echo "  Env file: ${ENV_FILE}"
echo ""
echo -e "${YELLOW}⚠️  Next steps (must be done on Stripe Dashboard):${NC}"
echo "  1. Verify webhook endpoint is active: https://dashboard.stripe.com/webhooks"
echo "  2. Check SSL/TLS is valid for your domain"
echo "  3. Monitor webhook deliveries in the Dashboard"
echo ""
