#!/bin/bash
set -e

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║         App Store Screenshots - Setup Guide              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Check what platform they want
PS3='Which platform? (1=Android, 2=iOS, 3=Both): '
options=("Android (Google Play)" "iOS (App Store)" "Both")
select opt in "${options[@]}"
do
    case $opt in
        "Android (Google Play)")
            echo ""
            echo "📱 ANDROID SCREENSHOTS"
            echo "======================"
            echo ""
            echo "Option A: Android Emulator (faster, visual)"
            echo "───────────────────────────────────────"
            echo ""
            echo "1. Open Android Studio → Device Manager → Create or run an emulator"
            echo ""
            echo "2. Install and run the debug APK:"
            echo "   adb install android/app/build/outputs/apk/debug/app-debug.apk"
            echo ""
            echo "3. Open the app and navigate to these screens:"
            echo ""
            echo "   📸 Screenshot 1: HOME SCREEN"
            echo "      - Tap app icon in emulator to launch"
            echo "      - Show music/content grid"
            echo "      - Use: Ctrl+S (Windows) or Cmd+S (Mac) to screenshot"
            echo ""
            echo "   📸 Screenshot 2: NOW PLAYING"
            echo "      - Tap a song to play"
            echo "      - Show player with controls"
            echo ""
            echo "   📸 Screenshot 3: ARTIST DETAIL"
            echo "      - Tap an artist card"
            echo "      - Show artist info + tracks"
            echo ""
            echo "   📸 Screenshot 4: SEARCH/DISCOVERY"
            echo "      - Open search or browse"
            echo ""
            echo "   📸 Screenshot 5: PLAYLISTS/SAVED"
            echo "      - Show bookmarked content"
            echo ""
            echo "4. Save all to: android/fastlane/screenshots/"
            echo ""
            echo "5. (Optional) Run fastlane guide:"
            echo "   fastlane android manual_screenshots"
            echo ""
            break
            ;;
        "iOS (App Store)")
            echo ""
            echo "📱 iOS SCREENSHOTS"
            echo "=================="
            echo ""
            echo "Option A: iOS Simulator (faster, visual)"
            echo "─────────────────────────────────────"
            echo ""
            echo "1. Start Xcode Simulator:"
            echo "   open -a Simulator"
            echo ""
            echo "2. In Simulator, open Safari → http://localhost:5001"
            echo "   (run 'python dev.py' in another terminal)"
            echo ""
            echo "3. Take 5 screenshots of these screens:"
            echo ""
            echo "   📸 Screenshot 1: HOME SCREEN"
            echo "      - App loads with content grid"
            echo ""
            echo "   📸 Screenshot 2: NOW PLAYING"
            echo "      - Play a song, show player"
            echo ""
            echo "   📸 Screenshot 3: ARTIST DETAIL"
            echo "      - Tap artist, show bio + tracks"
            echo ""
            echo "   📸 Screenshot 4: SEARCH/DISCOVERY"
            echo "      - Show search or discovery UI"
            echo ""
            echo "   📸 Screenshot 5: PLAYLISTS/SAVED"
            echo "      - Show bookmarks or playlists"
            echo ""
            echo "4. Take screenshots in Simulator:"
            echo "   Device → Screenshot (or Cmd+S)"
            echo ""
            echo "5. Save all to: ios/App/fastlane/screenshots/"
            echo ""
            echo "6. (Optional) Run fastlane guide:"
            echo "   fastlane ios screenshots"
            echo ""
            break
            ;;
        "Both")
            echo ""
            echo "📱 BOTH PLATFORMS"
            echo "================="
            echo ""
            echo "Follow Android steps first (faster setup)"
            echo "Then iOS steps (reuse similar screenshots)"
            echo ""
            echo "ANDROID:"
            echo "--------"
            echo "1. adb install android/app/build/outputs/apk/debug/app-debug.apk"
            echo "2. Take 5 screenshots → android/fastlane/screenshots/"
            echo ""
            echo "iOS:"
            echo "---"
            echo "1. open -a Simulator"
            echo "2. Safari → http://localhost:5001"
            echo "3. Take 5 screenshots → ios/App/fastlane/screenshots/"
            echo ""
            break
            ;;
        *) echo "Invalid option $REPLY";;
    esac
done

echo ""
echo "📝 UPLOAD TO STORES"
echo "==================="
echo ""
echo "Google Play Console:"
echo "  https://play.google.com/console"
echo "  → Your App → Google Play → Screenshots"
echo "  → Upload files from: android/fastlane/screenshots/"
echo ""
echo "App Store Connect:"
echo "  https://appstoreconnect.apple.com"
echo "  → Your App → TestFlight → Screenshots"
echo "  → Upload files from: ios/App/fastlane/screenshots/"
echo ""
echo "✅ Done!"
echo ""
