#!/usr/bin/env python3
"""Download videos from YouTube and upload to Google Cloud Storage.

This tool:
- Downloads videos from YouTube using yt-dlp
- Uploads to GCS bucket
- Generates metadata (duration, thumbnail, title, etc.)
- Optionally syncs to database

Usage:
    python tools/youtube_to_bucket.py --url https://www.youtube.com/watch?v=... --output-file output.json
    python tools/youtube_to_bucket.py --url https://www.youtube.com/watch?v=... --upload --bucket my-bucket
    python tools/youtube_to_bucket.py --playlist-url https://www.youtube.com/playlist?list=... --upload
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

try:
    from google.cloud import storage
    HAS_GCS = True
except ImportError:
    HAS_GCS = False


class YouTubeDownloader:
    def __init__(self, bucket: Optional[str] = None, prefix: str = "videos/", project: Optional[str] = None):
        self.bucket_name = bucket or os.getenv("AHOY_VIDEOS_GCS_BUCKET")
        self.prefix = prefix.strip("/") + "/"
        self.project_id = project or os.getenv("GCLOUD_PROJECT", "ahoyapp-indie")
        self.gcs_client = None
        if HAS_GCS and self.bucket_name:
            self.gcs_client = storage.Client(project=self.project_id)

    def _check_yt_dlp(self) -> bool:
        """Verify yt-dlp is installed and accessible."""
        if shutil.which("yt-dlp") is None:
            print("Error: yt-dlp not found on PATH")
            print("Install with: pip install yt-dlp")
            return False
        return True

    def _extract_video_info(self, url: str, output_path: Path) -> dict:
        """Use yt-dlp to download video and extract metadata."""
        if not self._check_yt_dlp():
            raise RuntimeError("yt-dlp not available")

        # Download video with info extraction
        cmd = [
            "yt-dlp",
            "-f", "best",  # Best quality format
            "--write-info-json",  # Save metadata JSON
            "--write-thumbnail",  # Download thumbnail
            "-o", str(output_path / "%(title)s.%(ext)s"),
            url,
        ]

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=1800)
            if result.returncode != 0:
                stderr = result.stderr or "Unknown error"
                raise RuntimeError(f"yt-dlp failed: {stderr}")
        except subprocess.TimeoutExpired:
            raise RuntimeError("Download timed out (30 min limit)")

        # Find the downloaded info JSON file
        json_files = list(output_path.glob("*.info.json"))
        if not json_files:
            raise RuntimeError("No metadata JSON generated by yt-dlp")

        with open(json_files[0], "r", encoding="utf-8") as f:
            info = json.load(f)

        return info

    def _upload_to_gcs(self, local_file: Path, remote_name: str) -> str:
        """Upload file to GCS and return public URL."""
        if not self.gcs_client:
            raise RuntimeError("GCS not configured (install google-cloud-storage)")

        bucket = self.gcs_client.bucket(self.bucket_name)
        blob = bucket.blob(f"{self.prefix}{remote_name}")
        blob.upload_from_filename(str(local_file))
        return f"https://storage.googleapis.com/{self.bucket_name}/{self.prefix}{remote_name}"

    def download_video(
        self,
        url: str,
        upload: bool = False,
        temp_dir: Optional[Path] = None,
    ) -> dict:
        """Download a single video from YouTube.

        Returns:
            dict with video metadata including download status, GCS URLs if uploaded
        """
        cleanup_temp = False
        if temp_dir is None:
            temp_dir = Path(tempfile.mkdtemp())
            cleanup_temp = True

        try:
            print(f"Downloading: {url}")
            info = self._extract_video_info(url, temp_dir)

            # Build metadata
            metadata = {
                "title": info.get("title", ""),
                "description": info.get("description", ""),
                "youtube_id": info.get("id", ""),
                "duration_seconds": info.get("duration", 0),
                "upload_date": info.get("upload_date", ""),
                "uploader": info.get("uploader", ""),
                "uploader_id": info.get("uploader_id", ""),
                "view_count": info.get("view_count", 0),
                "like_count": info.get("like_count"),
                "thumbnail_url": info.get("thumbnail", ""),
                "original_url": url,
                "downloaded_at": datetime.utcnow().isoformat(),
            }

            # Find video file
            video_files = [
                f
                for f in temp_dir.glob("*")
                if f.is_file() and f.suffix in {".mp4", ".mkv", ".webm", ".m4v"}
            ]
            if video_files:
                video_file = video_files[0]
                metadata["local_path"] = str(video_file)
                metadata["file_size"] = video_file.stat().st_size

                if upload and self.gcs_client:
                    print(f"Uploading to GCS: {self.bucket_name}")
                    video_url = self._upload_to_gcs(
                        video_file, f"{metadata['youtube_id']}{video_file.suffix}"
                    )
                    metadata["gcs_video_url"] = video_url
                    print(f"  Video: {video_url}")

            # Upload thumbnail if found
            thumb_files = list(temp_dir.glob("*.jpg")) + list(temp_dir.glob("*.png"))
            if thumb_files and upload and self.gcs_client:
                thumb_file = thumb_files[0]
                thumb_url = self._upload_to_gcs(
                    thumb_file, f"thumbnails/{metadata['youtube_id']}{thumb_file.suffix}"
                )
                metadata["gcs_thumbnail_url"] = thumb_url
                print(f"  Thumbnail: {thumb_url}")

            metadata["status"] = "success"
            return metadata

        finally:
            if cleanup_temp:
                shutil.rmtree(temp_dir, ignore_errors=True)

    def download_playlist(
        self,
        playlist_url: str,
        upload: bool = False,
        output_file: Optional[Path] = None,
    ) -> list[dict]:
        """Download all videos from a YouTube playlist."""
        results = []
        temp_base = Path(tempfile.mkdtemp())

        try:
            # Get playlist info
            cmd = [
                "yt-dlp",
                "--dump-single-json",
                "--no-warnings",
                "-O", "entries",
                playlist_url,
            ]
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                raise RuntimeError("Failed to fetch playlist info")

            try:
                entries = json.loads(result.stdout)
            except json.JSONDecodeError:
                raise RuntimeError("Could not parse playlist data")

            if not entries:
                print("No videos found in playlist")
                return []

            print(f"Found {len(entries)} videos in playlist")

            # Download each video
            for i, entry in enumerate(entries, 1):
                url = f"https://www.youtube.com/watch?v={entry.get('id')}"
                print(f"\n[{i}/{len(entries)}] {entry.get('title', 'Unknown')}")
                try:
                    video_dir = temp_base / f"video_{i}"
                    video_dir.mkdir(exist_ok=True)
                    metadata = self.download_video(url, upload=upload, temp_dir=video_dir)
                    results.append(metadata)
                except Exception as e:
                    print(f"  ERROR: {e}")
                    results.append({
                        "title": entry.get("title", "Unknown"),
                        "youtube_id": entry.get("id", ""),
                        "status": "failed",
                        "error": str(e),
                    })

            # Save results
            if output_file:
                output_file.parent.mkdir(parents=True, exist_ok=True)
                with open(output_file, "w", encoding="utf-8") as f:
                    json.dump(results, f, indent=2, default=str)
                print(f"\nResults saved: {output_file}")

            return results

        finally:
            shutil.rmtree(temp_base, ignore_errors=True)


def build_parser() -> argparse.ArgumentParser:
    """Build CLI argument parser."""
    parser = argparse.ArgumentParser(
        description="Download videos from YouTube and upload to Google Cloud Storage",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  Download and save metadata:
    python tools/youtube_to_bucket.py \\
      --url https://www.youtube.com/watch?v=... \\
      --output-file video.json

  Download and upload to GCS:
    python tools/youtube_to_bucket.py \\
      --url https://www.youtube.com/watch?v=... \\
      --upload --bucket my-videos-bucket

  Download entire playlist:
    python tools/youtube_to_bucket.py \\
      --playlist https://www.youtube.com/playlist?list=... \\
      --upload --output-file playlist.json

Environment variables:
  AHOY_VIDEOS_GCS_BUCKET  - Default GCS bucket (optional if --bucket specified)
""",
    )

    parser.add_argument(
        "--url",
        help="YouTube video URL to download",
    )
    parser.add_argument(
        "--playlist",
        help="YouTube playlist URL to download all videos from",
    )
    parser.add_argument(
        "--upload",
        action="store_true",
        help="Upload files to GCS bucket",
    )
    parser.add_argument(
        "--bucket",
        help="GCS bucket name (overrides AHOY_VIDEOS_GCS_BUCKET env var)",
    )
    parser.add_argument(
        "--prefix",
        default="videos/",
        help="GCS path prefix (default: videos/)",
    )
    parser.add_argument(
        "--output-file",
        type=Path,
        help="Save metadata to JSON file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be done without downloading",
    )

    return parser


def main(argv: Optional[list[str]] = None) -> int:
    """Main entry point."""
    parser = build_parser()
    args = parser.parse_args(argv)

    # Validate inputs
    if not args.url and not args.playlist:
        print("Error: Must provide --url or --playlist")
        parser.print_help()
        return 1

    if args.upload and not (args.bucket or os.getenv("AHOY_VIDEOS_GCS_BUCKET")):
        print("Error: --upload requires --bucket or AHOY_VIDEOS_GCS_BUCKET env var")
        return 1

    if args.dry_run:
        print("[DRY RUN] Would download:")
        if args.url:
            print(f"  Video: {args.url}")
        if args.playlist:
            print(f"  Playlist: {args.playlist}")
        if args.upload:
            print(f"  And upload to: {args.bucket or os.getenv('AHOY_VIDEOS_GCS_BUCKET')}/{args.prefix}")
        return 0

    try:
        downloader = YouTubeDownloader(bucket=args.bucket, prefix=args.prefix)

        if args.url:
            # Single video
            metadata = downloader.download_video(args.url, upload=args.upload)
            if args.output_file:
                args.output_file.parent.mkdir(parents=True, exist_ok=True)
                with open(args.output_file, "w", encoding="utf-8") as f:
                    json.dump(metadata, f, indent=2, default=str)
                print(f"Metadata saved: {args.output_file}")
            else:
                print(json.dumps(metadata, indent=2, default=str))
            return 0 if metadata.get("status") == "success" else 1

        else:
            # Playlist
            results = downloader.download_playlist(
                args.playlist,
                upload=args.upload,
                output_file=args.output_file,
            )
            success_count = sum(1 for r in results if r.get("status") == "success")
            print(f"\nCompleted: {success_count}/{len(results)} successful")
            return 0 if success_count == len(results) else 1

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
